#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
## Modified for Wayfire by WgpArch

# Import Current Theme
DIR="$HOME/.config/waybar1"
RASI="$DIR/powermenu.rasi"
CNFR="$DIR/confirm.rasi"

# Theme Elements
prompt="`hostname` (`echo $DESKTOP_SESSION`)"
mesg="Uptime : `uptime -p | sed -e 's/up //g'`"

# Options
layout=`cat ${RASI} | grep 'USE_ICON' | cut -d'=' -f2`
if [[ "$layout" == 'NO' ]]; then
	option_1=" Lock"
	option_2=" Logout"
	option_3=" Suspend"
	option_4=" Hibernate"
	option_5=" Reboot"
	option_6="⏻ Shutdown"
else
	option_1=""
	option_2=""
	option_3=""
	option_4=""
	option_5=""
	option_6="⏻"
fi
cnflayout=`cat ${CNFR} | grep 'USE_ICON' | cut -d'=' -f2`
if [[ "$cnflayout" == 'NO' ]]; then
	yes=' Yes'
	no=' No'
else
	yes=''
	no=''
fi

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "$prompt" \
		-mesg "$mesg" \
		-markup-rows \
		-theme ${RASI}
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6" | rofi_cmd
}

# Confirmation CMD
confirm_cmd() {
	rofi -dmenu \
		-p 'Confirmation' \
		-mesg 'Are you Sure?' \
		-theme ${CNFR}
}

# Ask for confirmation
confirm_exit() {
	echo -e "$yes\n$no" | confirm_cmd
}

# Confirm and execute
confirm_run () {	
	selected="$(confirm_exit)"
	if [[ "$selected" == "$yes" ]]; then
        ${1} && ${2} && ${3} && ${4}
    else
        exit
    fi	
}

# Execute Command (Wayfire-specific)
run_cmd() {
	if [[ "$1" == '--opt1' ]]; then
		# Lock: try hyprlock first, fallback to swaylock
		command -v hyprlock >/dev/null && hyprlock || swaylock -f
	elif [[ "$1" == '--opt2' ]]; then
		# Logout: kill Wayfire session
		confirm_run 'pkill wayfire'
	elif [[ "$1" == '--opt3' ]]; then
		# Suspend: pause audio, lock, then suspend
		confirm_run 'mpc -q pause' 'pamixer --mute' 'swaylock -f' 'systemctl suspend'
	elif [[ "$1" == '--opt4' ]]; then
		# Hibernate
		confirm_run 'systemctl hibernate'
	elif [[ "$1" == '--opt5' ]]; then
		# Reboot
		confirm_run 'systemctl reboot'
	elif [[ "$1" == '--opt6' ]]; then
		# Shutdown
		confirm_run 'systemctl poweroff'
	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    "$option_1") run_cmd --opt1 ;;
    "$option_2") run_cmd --opt2 ;;
    "$option_3") run_cmd --opt3 ;;
    "$option_4") run_cmd --opt4 ;;
    "$option_5") run_cmd --opt5 ;;
    "$option_6") run_cmd --opt6 ;;
esac
